import { QuestionSet } from "@/types";

// Example mock data
export const questionSets: QuestionSet[] = [
  {
    id: "set1",
    name: "General Knowledge - Set A",
    questions: [
      {
        id: "q1",
        question: "What is the capital of France?",
        option1: "Berlin",
        option2: "Madrid",
        option3: "Paris",
        option4: "Rome",
        correctOption: "option3",
        timer: "30",
      },
      {
        id: "q2",
        question: "What is 2 + 2?",
        option1: "3",
        option2: "4",
        option3: "5",
        option4: "6",
        correctOption: "option2",
        timer: "30",
      },
      {
        id: "q3",
        question: "Who wrote Hamlet?",
        option1: "Shakespeare",
        option2: "Hemingway",
        option3: "Tolkien",
        option4: "Rowling",
        correctOption: "option1",
        timer: "30",
      },
      {
        id: "q4",
        question: "What is the boiling point of water?",
        option1: "90°C",
        option2: "100°C",
        option3: "80°C",
        option4: "120°C",
        correctOption: "option2",
        timer: "30",
      },
      {
        id: "q5",
        question: "Which planet is known as the Red Planet?",
        option1: "Mars",
        option2: "Venus",
        option3: "Jupiter",
        option4: "Saturn",
        correctOption: "option1",
        timer: "30",
      },
      {
        id: "q6",
        question: "What is the largest ocean on Earth?",
        option1: "Atlantic",
        option2: "Pacific",
        option3: "Indian",
        option4: "Arctic",
        correctOption: "option2",
        timer: "30",
      },
      {
        id: "q7",
        question: "Which country is famous for the Eiffel Tower?",
        option1: "Spain",
        option2: "Italy",
        option3: "France",
        option4: "Germany",
        correctOption: "option3",
        timer: "30",
      },
      {
        id: "q8",
        question: "How many continents are there?",
        option1: "5",
        option2: "6",
        option3: "7",
        option4: "8",
        correctOption: "option3",
        timer: "30",
      },
    ],
  },
  {
    id: "set2",
    name: "Science Quiz - Set B",
    questions: [
      {
        id: "q9",
        question: "What is the chemical symbol for water?",
        option1: "O2",
        option2: "CO2",
        option3: "H2O",
        option4: "NaCl",
        correctOption: "option3",
        timer: "30",
      },
      {
        id: "q10",
        question: "What gas do plants absorb from the atmosphere?",
        option1: "Oxygen",
        option2: "Nitrogen",
        option3: "Carbon Dioxide",
        option4: "Hydrogen",
        correctOption: "option3",
        timer: "30",
      },
      {
        id: "q11",
        question: "What force pulls objects toward Earth?",
        option1: "Magnetism",
        option2: "Electricity",
        option3: "Gravity",
        option4: "Friction",
        correctOption: "option3",
        timer: "30",
      },
    ],
  },
  {
    id: "set3",
    name: "Math Challenge - Set C",
    questions: Array.from({ length: 50 }).map((_, idx) => ({
      id: `mq${idx + 1}`,
      question: `What is ${idx + 1} + ${idx + 1}?`,
      option1: `${(idx + 1) * 2 - 1}`,
      option2: `${(idx + 1) * 2}`,
      option3: `${(idx + 1) * 2 + 1}`,
      option4: `${(idx + 1) * 2 + 2}`,
      correctOption: "option2",
      timer: "30",
    })),
  },
];
